#!/bin/bash

function install_composer() {
    local php_bin=php
    local pkg=composer.phar

    mkdir -p ${OPENSHIFT_DATA_DIR}/.composer
    mkdir -p ${OPENSHIFT_DATA_DIR}/bin
    export COMPOSER_HOME=${OPENSHIFT_DATA_DIR}/.composer

    pushd ${OPENSHIFT_DATA_DIR}/bin/

    if [[ ! -e ${pkg} ]]; then
        echo "Downloading ${pkg}."
        wget http://getcomposer.org/${pkg}
        chmod a+x ${pkg}
    fi

    echo "Updating ${pkg}."
    ${php_bin} ${pkg} self-update

    popd

    # Setup vendor dir
    pushd ${OPENSHIFT_REPO_DIR}/
    echo "Install vendors."
    ${php_bin} ${OPENSHIFT_DATA_DIR}/bin/${pkg} -n install -o
    popd
}

install_composer
